// Fixed-size local brand assets use native images.
/* oxlint-disable next/no-img-element */
import { ArrowRight, ExternalLink, Cloud } from 'lucide-react';
import { SimpleStory } from '@/components/simple-story';
import { TechnicalGuide } from '@/components/technical-guide';

export default function Home() {
  return <div id="top" className="app-shell">
    <header className="compact-header">
      <h1 className="site-title"><a href="#top" className="compact-brand" aria-label="How do passkeys work — back to top"><span className="compact-logo"><img src="/mystic-dragon.webp" alt="" width="27" height="31"/></span><span>How do passkeys work</span></a></h1>
      <nav aria-label="Page links"><a href="#questions" className="faq-link">FAQ <ArrowRight size={16}/></a><a className="github-link" href="https://github.com/mysticcoders/howdopasskeyswork" target="_blank" rel="noreferrer" aria-label="View source on GitHub (opens in a new tab)" title="View source on GitHub"><svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M12 .297C5.37.297 0 5.67 0 12.297c0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.043-1.61-4.043-1.61-.546-1.387-1.333-1.756-1.333-1.756-1.09-.745.083-.73.083-.73 1.205.084 1.838 1.237 1.838 1.237 1.07 1.835 2.807 1.305 3.492.998.108-.776.418-1.305.762-1.605-2.665-.305-5.467-1.334-5.467-5.93 0-1.31.468-2.38 1.235-3.22-.135-.303-.54-1.524.105-3.176 0 0 1.005-.322 3.3 1.23a11.5 11.5 0 0 1 3-.404c1.02.005 2.045.138 3 .404 2.28-1.552 3.285-1.23 3.285-1.23.645 1.652.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg></a></nav>
    </header>
    <main>
      <p className="passkey-intro">A passkey lets your device prove it’s you using a public key the website saved when you set it up—no password to remember or type.</p>
      <SimpleStory />
      <section className="questions" id="questions"><div><span className="eyebrow">GOOD TO KNOW</span><h2>Your everyday questions.</h2><Cloud className="question-icon" size={48}/></div><div className="faqs">{[
        ['Do I need another way to sign in first?', 'For an existing account, the website must authorize adding a passkey—often after you sign in with your current method. A new account can start with a passkey, without a password. Email verification or identity checks depend on the website. Once set up, a passkey can be your sign-in method; unlocking your device lets you use it.'],
        ['Where is my passkey saved?', 'Usually in a password manager, such as Apple Passwords, Google Password Manager, or 1Password. Passkeys can also be saved on the device itself (for example, Windows Hello) or on a physical security key. You choose from the options your device offers when you save it.'],
        ['What if I lose my phone?', 'Some passkeys sync: your password manager can make them available on another supported device. Others stay on just one device or security key. For those, you need another sign-in method or the website’s account recovery. Set up a backup before you need it.'],
        ['Can I use another computer?', 'Often, yes. Your password manager may make your passkey available there. Some websites also let you sign in using your nearby phone by scanning a QR code. The options depend on your devices and the website.'],
        ['Does the website get my fingerprint or face?', 'No. Your device checks your face, fingerprint, or device PIN locally. That gives it permission to use your passkey. The website receives proof that your device has the right key, not your face, fingerprint, or PIN.'],
        ['How do I get a passkey?', 'Create one on each website that supports them, either during sign-up or from an existing account’s security settings after signing in. Choose where to save it and approve. Your device or provider creates the keys; the website saves the public part with your account. You do not choose or type a new password.'],
        ['Do I still need a password?', 'That depends on the website. Some replace passwords with passkeys; others keep both. Check your sign-in and recovery options before removing a password.'],
        ['Does this stop every kind of attack?', 'No. A fake website cannot use the passkey for the real website, but someone could still attack your device, steal an already signed-in session, or abuse account recovery. Passkeys protect an important part of signing in.'],
        ['Is this demo creating a real passkey?', 'No. Everything here is a simulation. It does not collect biometric data, save a real passkey, or sign you into an account. Mystic Coders is our example website; this demo does not claim it offers passkey sign-in.'],
      ].map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
      <TechnicalGuide />
      <section className="providers" aria-labelledby="providers-title"><div className="providers-copy"><h2 id="providers-title">Where you might save a passkey</h2><p>You may already use one of these password managers. They can save passkeys too.</p><p className="hardware-note">A physical security key, such as a YubiKey, can also keep passkeys. Those passkeys stay on that key.</p></div><div className="provider-logos"><a href="https://support.apple.com/en-us/120758" target="_blank" rel="noreferrer"><span className="provider-icon"><img src="/apple.svg" alt="" width="24" height="28"/></span><span>Apple<small>Passwords</small></span><ExternalLink size={12}/></a><a href="https://passwords.google/" target="_blank" rel="noreferrer"><span className="provider-icon"><img src="/google-password-manager.webp" alt="" width="30" height="30"/></span><span>Google<small>Password Manager</small></span><ExternalLink size={12}/></a><a href="https://1password.com/product/passkeys" target="_blank" rel="noreferrer"><span className="provider-icon"><img src="/1password.svg" alt="" width="30" height="30"/></span><span>1Password</span><ExternalLink size={12}/></a></div></section>
    </main><footer><a className="footer-maker" href="https://mysticcoders.com" target="_blank" rel="noreferrer"><img className="maker-dragon" src="/mystic-dragon.webp" alt="" width="23" height="27"/>Made by <strong>Mystic Coders</strong> <ExternalLink size={13}/></a><span>A little less mystery. A little more understanding.</span><div><a href="https://fidoalliance.org/passkeys/" target="_blank" rel="noreferrer">FIDO Alliance <ExternalLink size={13}/></a><a href="https://www.w3.org/TR/webauthn-3/" target="_blank" rel="noreferrer">WebAuthn standard <ExternalLink size={13}/></a></div></footer>
  </div>;
}
